name: First workflow
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello-world"
      - name: print bye
        run: echo "done-bye"
